spring:
  application.name: gateway
  cloud: 
    gateway:
      default-filters:
      - PrefixPath=/
      routes:
      #=====================================================================
      - id: cards
        uri: lb://flashcard 
       # uri: http://localhost:8081
        predicates:
        - Path=/flashcard/**
        filters:      
        - StripPrefix=1
        - name: CircuitBreaker
          args:
            name:  flashcard-fallback
            fallbackUri:  forward:/fallback/flashcard
        
       #=======================================================================
      - id: quiz
        uri: lb://quiz
        #uri: http://localhost:8082
        predicates:
        - Path=/quiz/**
        filters:
        - StripPrefix=1
  
  
